/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
}

repositories {
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT")
}

tasks.register<Jar>("buildPlugin") {
    archiveBaseName.set("reporting")
    destinationDirectory.set(file("$buildDir/libs"))
    from(sourceSets.main.get().output)
    manifest {
        attributes(
            "Main-Class" to "yakyoku.global",  // Change this to your actual main class path
            "Implementation-Title" to "Reporting",
            "Implementation-Version" to "1.0"
        )
    }
}

tasks.jar {
    manifest {
        attributes["paperweight-mappings-namespace"] = "spigot"
    }
}