name: Reporting
version: 1.0.0
main: fr.yakyoku.reporting.main.ReportingPlugin
description: A simple reporting plugin allowing users to save complaints about players and have allowed users consult and file those complaints.
api-version: '1.20'
commands:
  report:
    description: Report a player
    usage: /report <name> <motive> <optComment>
    permission: yakyoku.reporting.report
  solve:
    description: Close a report
    usage: /solve <reportId> <status> <optComment>
    permission: yakyoku.reporting.solve
  read:
    description: Get details of a report
    usage: /read <reportId>
    permission: yakyoku.reporting.read
  readall:
    description: Get a list of reports
    usage: /readall <optPage>
    permission: yakyoku.reporting.read
permissions:
  yakyoku.reporting.report:
    description: Allows posting reports
    default: true
  yakyoku.reporting.solve:
    description: Allows closure of reports
    default: false
  yakyoku.reporting.read:
    description: Allows read access to the reports
    default: false

folia-supported: true